apiVersion: v1
kind: Service
metadata:
  name: pull-request-tracking-system
spec:
  selector:
    app: pull-request-tracking-system
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080